@startuml Algorithm

package "ca.mcmaster.se2aa4.island.team209" {
    class Runner {
        - main(String[]): void
    }
    class Point {
        
    }
    interface Movement {
        + needsInstruction(): boolean
        + goDirection(Direction): void
        + goRight(): void
        + goLeft(): void
        + goForward(): void
        + useRadar(Direction): void
        + scan(): void
        + stop(): void
        + getNextInstruction(): String
    }
    class JSONMover {
        + goRight(): void
        + goLeft(): void
        + goForward(): void
        + useRadar(Direction): void
        + needsInstruction(): boolean
        + goDirection(Direction): void
        + scan(): void
        + stop(): void
        + getNextInstruction(): String
    }
    class ExploringDrone {
        
        + ExploringDrone(int, int, int, Direction)
        + turnRight(): void
        + turnLeft(): void
        + goForward(): void
        + getLastScan(): Direction
        + setLastScan(Direction): void
        + staticPoint(): Point
    }
    abstract class Drone {
        + getCoordinates(): Point
        + getBattery(): int
        + getDirection(): Direction
        
    }
    enum Direction {
        N
        E
        S
        W
    }
}

package "ca.mcmaster.se2aa4.island.team209.Radio" {
    class IslandAlgorithm {
        
        + decision(): String
        + takeInfo(String): void
        + finalReport(): String
    }
    interface ExploreAlgorithm {
        + decision(): String
        + takeInfo(String): void
        + finalReport(): String
    }
    class Explorer {
        - control: ExploreAlgorithm
        
        + takeDecision(): String
        + acknowledgeResults(String): void
        + deliverFinalReport(): String
    }
}

package "ca.mcmaster.se2aa4.island.team209.POI" {
    class NearestCreekToSitePOIHandler {
        
    }
    class POI {
        
        + POI(String, Point)
        + closerPoint(POI, POI): POI
    }
    interface POIHandler {
        + addPoint(String, POI): void
        + getReport(): String
    }
}


IslandAlgorithm *--  Movement
IslandAlgorithm *--  POIHandler
IslandAlgorithm *--  ExploringDrone
IslandAlgorithm *--  Point
IslandAlgorithm *--  Direction
IslandAlgorithm ..|> ExploreAlgorithm
Explorer *-- ExploreAlgorithm
POI *-- Point
ExploringDrone *-- Direction
ExploringDrone *-- Point
ExploringDrone --|> Drone
JSONMover ..|> Movement
JSONMover *-- ExploringDrone
NearestCreekToSitePOIHandler ..|> POIHandler
NearestCreekToSitePOIHandler *-- POI


